version: 2.1


jobs:
  build:
    working_directory: ~/circleci-demo-python-aws
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install
          command: make install
      - run:
          name: Lint
          command: make lint
